server.port=8081

spring.mongodb.uri=mongodb+srv://malepatipremkumarreddy:Mpremkreddy@eccomerce.sgqwrhn.mongodb.net/Unieven?retryWrites=true&w=majority

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unievenwebsite@gmail.com
spring.mail.password=jvyz fmwj etri entz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true